/**
 * Layout Provider (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * This wraps the LayoutProvider from next-workflow-builder with plugin
 * initialization. Import this instead of importing LayoutProvider directly
 * from "next-workflow-builder/components".
 *
 * Usage in your layout.tsx:
 *   import { LayoutProvider } from "@/lib/layout-provider";
 */
"use client";

// Side-effect import: registers all discovered plugins into the registry
import "@/plugins/index";

// Re-export the LayoutProvider with plugins pre-initialized
export { LayoutProvider } from "next-workflow-builder/components";
