/**
 * Output Display Configs (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * This file is CLIENT-SAFE and can be imported in client components.
 * It maps action IDs to their output display configuration.
 *
 * Generated configs: 0
 */

export type OutputDisplayConfig = {
  type: "image" | "video" | "url";
  field: string;
};

/**
 * Output display configs - maps action IDs to their display configuration
 * Used for rendering outputs in the workflow runs panel
 */
export const OUTPUT_DISPLAY_CONFIGS: Record<string, OutputDisplayConfig> = {

};

/**
 * Get the output display config for an action type
 */
export function getOutputDisplayConfig(actionType: string): OutputDisplayConfig | undefined {
  return OUTPUT_DISPLAY_CONFIGS[actionType];
}
