/**
 * Integration Types (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * To add a new integration type:
 * 1. Create a plugin in plugins/ directory, OR
 * 2. Add a system integration to SYSTEM_INTEGRATION_TYPES in discover-plugins.ts
 * 3. Run: pnpm discover-plugins
 *
 * Generated types: ai-gateway, blob, clerk, database, facebook, fal, firecrawl, github, linear, loop, perplexity, resend, slack, stripe, superagent, switch, tixr, v0, webflow, youtube
 */

// Integration type union - plugins + system integrations
export type IntegrationType = "database" | "ai-gateway";

// Generic config type - plugins define their own keys via formFields[].configKey
export type IntegrationConfig = Record<string, string | undefined>;
