/* AUTO-GENERATED BY next-workflow-builder — do not edit */
import { createWorkflowApiHandler } from 'next-workflow-builder';

const handler = createWorkflowApiHandler();

export { handler as GET, handler as POST, handler as PUT, handler as DELETE };
